#ifndef FIRST_SERVICE_GLOBAL_H
#define FIRST_SERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FIRST_SERVICE_LIBRARY)
#  define FIRSTSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define FIRSTSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FIRST_SERVICE_GLOBAL_H
