#ifndef SECOND_SERVICE_GLOBAL_H
#define SECOND_SERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SECOND_SERVICE_LIBRARY)
#  define SECONDSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SECONDSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SECOND_SERVICE_GLOBAL_H
