#ifndef SECOND_MODULE_GLOBAL_H
#define SECOND_MODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SECOND_MODULE_LIBRARY)
#  define SECONDMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SECONDMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SECOND_MODULE_GLOBAL_H
